### ISSUE TITLE
Support current tensorflow version

### ISSUE THREAD

**Issue by wuriyanto48** [erickrf/treernn#1]
First, thank for this awesome project. But can you update this project to support with Tensorflow V 2?. Thank you

**Comment by erickrf** [comment]
Hello! Well, actually something very weird happened: this repository was a fork of another one, which I assume was deleted and now it shows mine as an original work. 

I intended to work a bit with the Tree RNNs but never did and forgot about this repository. I suggest you searching for other repositories, some of them might be more up to date.
